- name: deploy
  hosts: all
  user: ubuntu
  tasks:
    - name: Creates directory
      file:
        path: ~/web
        state: directory

    - name: Copy index test page
      template:
        src: backend
        dest: ~/web

    - name: Executing node
      shell: |
        pm2 start ~/web/backend/main.ts -f