- name: deploy
  hosts: all
  user: ubuntu
  tasks:
    - name: Creates directory
      become: yes
      file:
        path: ~/web
        state: directory
    - name: get backend
      become: yes
      copy:
        src: ../../../../dist
        dest: web
    - name: start 
      become: yes
      shell: |    
        cd /home/ubuntu/web/dist/
        pm2 start main.js --name backend