- name: deploy
  hosts: all
  user: ubuntu
  tasks:
    - name: Creates directory
      file:
        path: ~/web
        state: directory
    - name: get backend
      become: yes
      unarchive:
        src: /tmp/workspace/backend.tar.gz
        dest: ~/web
        remote_src: yes
    - name: start server
      become: yes
      shell: |    
        cd ~/web
        pm2 start main.js